[package]
name = "fpdb"
version = "0.1.0"
edition = "2024"

[dependencies]
fpcommon = { path = "../fpcommon/" }

uuid = { version = "1.18.0", features = ["serde"]}
serde = { version = "1.0.219", features = ["derive"]}
chrono = { version = "0.4.41", features = ["serde"]}
