[package]
name = "fpdb"
version = "0.1.0"
edition = "2024"

[dependencies]
fpcommon = { path = "../fpcommon/" }

serde = { version = "1.0.225", features = ["derive"]}
chrono = { version = "0.4.42", features = ["serde"]}
rusqlite = { version = "0.37.0", features = ["bundled", "chrono"] }
