[package]
name = "fpcommon"
version = "0.1.0"
edition = "2024"

[dependencies]
uuid = { version = "1.18.0", features = ["v4", "serde"]}
serde = { version = "1.0.219", features = ["derive"]}
chrono = { version = "0.4.41", features = ["serde"]}
